site_name: Dataformer
site_url: https://docs.dataformer.ai/
repo_name: DataformerAI/dataformer
repo_url: https://github.com/DataformerAI/dataformer
watch:
  - src

# Navigation
nav:
  - "": index.md
  - 🚀 Get Started:
      - getstarted/index.md
      - Installation: getstarted/install.md
      - Generate Synthetic Dataset: getstarted/dataset_generation.md
  - ✅️ Tutorials:
      - tutorials/index.md
      - AI Characters Dataset:  tutorials/ai_character.md
      - PDF to QA Dataset: tutorials/pdf_qa.md
  - 🛠️ Components:
      - components/index.md
      - Async LLM: components/async_llm.md
      - Evol Instruct: components/evol_instruct.md
      - Evol Quality: components/evol_quality.md
  - ❤️ Community: community/index.md

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Material-Docs Theme
theme:
  name: material
  logo: _static/dataformer.png
  favicon: _static/dataformer.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: dataformer_light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dataformer_dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ["./docs/extra/components/"]

# Extra CSS
extra_css:
  - extra/style.css

# Plugins
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
plugins:
  - search
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_CI, false]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [MKDOCS_CI, false]
      repository: DataformerAI/dataformer
      branch: main
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
  - glightbox

extra_javascript:
  - _static/js/mathjax.js
  - _static/js/header_border.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - _static/js/toggle.js
